export const bankOption = [
    { value: 'vietcombank', label: 'Ngân hàng TMCP Ngoại thương Việt Nam (Vietcombank)' },
    { value: 'vietinbank', label: 'Ngân hàng TMCP Công thương Việt Nam (VietinBank)' },
    { value: 'bidv', label: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)' },
    { value: 'agribank', label: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam (Agribank)' },
    { value: 'techcombank', label: 'Ngân hàng TMCP Kỹ thương Việt Nam (Techcombank)' },
    { value: 'vpbank', label: 'Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)' },
    { value: 'mbbank', label: 'Ngân hàng TMCP Quân đội (MB Bank)' },
    { value: 'sacombank', label: 'Ngân hàng TMCP Sài Gòn Thương Tín (Sacombank)' },
    { value: 'acb', label: 'Ngân hàng TMCP Á Châu (ACB)' },
    { value: 'hdbank', label: 'Ngân hàng TMCP Phát triển TP.HCM (HDBank)' },
    { value: 'ocb', label: 'Ngân hàng TMCP Phương Đông (OCB)' },
    { value: 'shb', label: 'Ngân hàng TMCP Sài Gòn - Hà Nội (SHB)' },
    { value: 'scb', label: 'Ngân hàng TMCP Sài Gòn (SCB)' },
    { value: 'dongabank', label: 'Ngân hàng TMCP Đông Á (DongA Bank)' },
    { value: 'eximbank', label: 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam (Eximbank)' },
    { value: 'vib', label: 'Ngân hàng TMCP Quốc tế Việt Nam (VIB)' },
    { value: 'msb', label: 'Ngân hàng TMCP Hàng Hải Việt Nam (MSB)' },
    { value: 'seabank', label: 'Ngân hàng TMCP Đông Nam Á (SeABank)' },
    { value: 'bacabank', label: 'Ngân hàng TMCP Bắc Á (Bac A Bank)' },
    { value: 'pvcombank', label: 'Ngân hàng TMCP Đại chúng Việt Nam (PVcomBank)' },
    { value: 'vietabank', label: 'Ngân hàng TMCP Việt Á (VietABank)' },
    { value: 'lpbank', label: 'Ngân hàng TMCP Bưu Điện Liên Việt (LPBank)' },
    { value: 'baovietbank', label: 'Ngân hàng TMCP Bảo Việt (BaoVietBank)' },
    { value: 'namabank', label: 'Ngân hàng TMCP Nam Á (NamABank)' },
    { value: 'pgbank', label: 'Ngân hàng TMCP Xăng Dầu Petrolimex (PG Bank)' },
    { value: 'kienlongbank', label: 'Ngân hàng TMCP Kiên Long (KienLongBank)' },
    { value: 'vietcapitalbank', label: 'Ngân hàng TMCP Bản Việt (VietCapitalBank)' },
    { value: 'oceanbank', label: 'Ngân hàng Đại Dương (OceanBank)' },
    { value: 'gpbank', label: 'Ngân hàng TMCP Dầu khí Toàn Cầu (GPBank)' },
    { value: 'abbank', label: 'Ngân hàng TMCP An Bình (ABBank)' },
    { value: 'hsbc', label: 'Ngân hàng HSBC Việt Nam' },
    { value: 'citibank', label: 'Ngân hàng Citibank Việt Nam' },
    { value: 'standardchartered', label: 'Ngân hàng Standard Chartered Việt Nam' },
    { value: 'shinhanbank', label: 'Ngân hàng Shinhan Việt Nam' },
    { value: 'woori', label: 'Ngân hàng Woori Việt Nam' },
    { value: 'sumitomo', label: 'Ngân hàng Sumitomo Mitsui Việt Nam' },
    { value: 'mizuho', label: 'Ngân hàng Mizuho Việt Nam' },
    { value: 'dbs', label: 'Ngân hàng DBS Việt Nam' },
    { value: 'ocbc', label: 'Ngân hàng OCBC Việt Nam' },
    { value: 'maybank', label: 'Ngân hàng Maybank Việt Nam' },
    { value: 'publicbank', label: 'Ngân hàng Public Bank Việt Nam' },
    { value: 'rabobank', label: 'Ngân hàng Rabobank Việt Nam' },
    { value: 'anz', label: 'Ngân hàng ANZ Việt Nam' },
    { value: 'ufj', label: 'Ngân hàng MUFG Việt Nam' },
    { value: 'uob', label: 'Ngân hàng UOB Việt Nam' },
    { value: 'cimb', label: 'Ngân hàng CIMB Việt Nam' },
    { value: 'vietbank', label: 'Ngân hàng TMCP Việt Nam (VietBank)' },
    { value: 'vietrussianbank', label: 'Ngân hàng Liên doanh Việt Nga' },
    { value: 'saigonbank', label: 'Ngân hàng TMCP Sài Gòn Công Thương (SaigonBank)' },
    { value: 'abcbank', label: 'Ngân hàng TMCP ABC' },
    { value: 'asbank', label: 'Ngân hàng TMCP ASBank' },
    { value: 'tcbank', label: 'Ngân hàng TMCP TC Việt Nam' },
    { value: 'trustbank', label: 'Ngân hàng TMCP TrustBank' },
    { value: 'southeastbank', label: 'Ngân hàng Đông Nam Việt Nam' },
    { value: 'centralbank', label: 'Ngân hàng Trung ương Việt Nam' },
    { value: 'southbank', label: 'Ngân hàng Nam Việt' },
    { value: 'northbank', label: 'Ngân hàng Bắc Việt' },
    { value: 'centralbankasia', label: 'Ngân hàng Trung tâm Châu Á' },
    { value: 'tpbank', label: 'Ngân hàng TMCP Tiên Phong (TPBank)' },
    { value: 'lpbank', label: 'Ngân hàng TMCP LienVietPostBank (LPBank)' },
    { value: 'ftbbank', label: 'Ngân hàng TMCP FTB Việt Nam' },
    { value: 'vncbank', label: 'Ngân hàng TMCP VNC' }
  ];
  